// Coded by @sr-engineer
// Tools: handoff state read/write with format enforcement

import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import { markStateRead } from "../guards/session.js";

interface HandoffState {
  active_feature: string;
  status: string;
  last_updated: string;
  completed: string[];
  pending: string[];
}

function getHandoffPath(workspacePath: string): string {
  return path.join(workspacePath, ".current", "handoff.md");
}

function ensureDir(workspacePath: string): void {
  const dir = path.join(workspacePath, ".current");
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

/**
 * Parse handoff.md YAML frontmatter + checkbox content into structured JSON.
 * Returns null if file doesn't exist.
 */
export function parseHandoff(workspacePath: string): HandoffState | null {
  const handoffPath = getHandoffPath(workspacePath);
  if (!fs.existsSync(handoffPath)) return null;

  const content = fs.readFileSync(handoffPath, "utf-8");

  // Parse YAML frontmatter with js-yaml (handles quotes, colons in values, etc.)
  const frontmatter: Record<string, unknown> = {};
  const yamlMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (yamlMatch) {
    try {
      const parsed = yaml.load(yamlMatch[1]);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        Object.assign(frontmatter, parsed as Record<string, unknown>);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      throw new Error(`Failed to parse handoff.md frontmatter: ${message}`);
    }
  }

  const asString = (v: unknown): string => (typeof v === "string" ? v : v == null ? "" : String(v));

  // Parse checkboxes
  const completed = [...content.matchAll(/- \[x\] (.+)/g)].map((m) => m[1]);
  const pending = [...content.matchAll(/- \[ \] (.+)/g)].map((m) => m[1]);

  return {
    active_feature: asString(frontmatter.active_feature),
    status: asString(frontmatter.status),
    last_updated: asString(frontmatter.last_updated),
    completed,
    pending,
  };
}

/**
 * Read handoff state. Marks session as "state read" for guard enforcement.
 */
export function readHandoffState(workspacePath: string): string {
  markStateRead(workspacePath);

  const state = parseHandoff(workspacePath);
  if (!state) {
    return JSON.stringify({
      exists: false,
      message: "No handoff state found. This is a fresh project — initialize by calling sdd_update_state.",
    });
  }
  return JSON.stringify({ exists: true, ...state });
}

/**
 * Write handoff state with enforced formatting.
 * Guarantees valid YAML frontmatter + Markdown checkbox structure.
 */
export function writeHandoffState(
  workspacePath: string,
  activeFeature: string,
  status: string,
  completedTasks: string[],
  pendingNotes: string[]
): string {
  ensureDir(workspacePath);
  const handoffPath = getHandoffPath(workspacePath);
  const now = new Date().toISOString();

  const completedList = completedTasks.length
    ? completedTasks.map((t) => `- [x] ${t}`).join("\n")
    : "- 無";
  const pendingList = pendingNotes.length
    ? pendingNotes.map((t) => `- [ ] ${t}`).join("\n")
    : "- 無";

  // Serialize frontmatter via js-yaml so quotes/colons/newlines in values are escaped safely.
  const frontmatter = yaml
    .dump(
      { active_feature: activeFeature, status, last_updated: now },
      { lineWidth: -1, forceQuotes: true, quotingType: '"' }
    )
    .trimEnd();

  const content = `---
${frontmatter}
---
# 📍 任務交接狀態 (Handoff State)

## ✅ 已完成 (Completed)
${completedList}

## ⚠️ 待辦與交接 (Pending & Handoff Notes)
${pendingList}

---
> 🤖 **System Note**: Auto-generated by SDD MCP Server v2.0. Do NOT edit manually.
`;

  fs.writeFileSync(handoffPath, content, "utf-8");
  return JSON.stringify({ success: true, path: handoffPath, updated_at: now });
}
